package com.example.tasktylium.model

data class Instruments(
        val _id:String,
        val id:String,
        val assetClass:String,
        val name:String,
        val canonical_symbol:String,
        val source:String,
        val source_symbol:String,
        val _priceMultiplier:Int,
        val _tdKey:Int,
        val aggressiveCommissionRate:String,
        val contractInfoCurrency:String,
        val contractSize:Double,
        val contractUnitOfMeasure:String,
        val dailyInterestRateBasis:String,
        val longSwapPoints:String,
        val margin:Double,
        val maximumPositionThreshold:String,
        val minimumCommission:String,
        val minimumOrderQuantity:String,
        val passiveCommissionRate:String,
        val priceIncrement:String,
        val quantityIncrement:String ,
        val retailVolatilityBandPercentage: String,
        val shortSwapPoints: String,
        val startTime: String,
        val stopBuffer: Int,
        val swapPointValue: String,
        //val timestamp: Timestamp,
        val tm: String,
        val tradingDays: List<String>,
        val tradingFrom: Int,
        val tradingShouldBeOpen: Boolean,
        val tradingStatus: String,
        val tradingStatusChanged: Boolean,
        val tradingTimezone: String,
        val tradingTo: Int,
        val trustedSpread: Double,
        val unitPrice: String,
        val venue: String,
        val volatilityBandPercentage: String,
        val wasHidden: Boolean,
        val _altGroups: List<String>,
       // val _open: Int,
        val _priceDP: Int,
        val _lastClose: Float,
        val _group: String,
        val _rank: Int,
        val _count: Int,
        val _channel: String


) {

}
